CW_RESOURCE_ALIASES = {
    "entry.menu": "f4.png",
    "entry.cosmic_strife": "cosmic_strife.png",
    "entry.start": "start_currency_wars.png",
    "entry.new": "enter_game.png",
    "entry.continue": "continue_progress.png",
    "entry.start_game": "start_game.png",
    "entry.difficulty.highest": "return_highest_rank.png",
    "entry.difficulty.lowest": "down_arrow.png",
    "guide.strategy": "strategy.png",
    "guide.enter_code": "enter_strategy_code.png",
    "guide.confirm": "ensure2.png",
    "guide.apply": "apply_strategy.png",
    "stage.preparation": "preparation_stage.png",
    "stage.shop": "fold.png",
    "stage.replenish": "replenish_stage.png",
    "stage.encounter": "encounter_node.png",
    "stage.invest": "select_invest_strategy.png",
    "stage.boss_preview": "click_blank.png",
    "stage.fortune": "fortune_teller.png",
    "stage.event": "collect.png",
    "stage.settle": "next_step.png",
    "stage.game_over": "start_currency_wars.png",
}
